services:
  node-app:
    container_name: food-delivery
    build: .
    ports:
      - "4000:4000"
    # env_file:
    #   - ./.env
    depends_on:
      - redis
      - postgres


  redis:
    image: redis


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app


  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
